### ISSUE TITLE
Make output directory (permanently) configurable

### ISSUE THREAD

**Issue by Schweinepriester** [MrMitch/realdebrid-CLI#14]
First of all: Great that this exists, thank you very much :)

I'd like to have the option to configure an output directory permanently, e.g. via config-file.

Maybe like [beets](http://beets.radbox.org/) does it, [using a `.yaml`-file](http://beets.readthedocs.org/en/v1.3.13/reference/config.html)?

**Comment by MrMitch** [comment]
Hi! 
Thank you for your interest in the project. This seems like a good idea, especially since `rdcli` is already using a configuration file (`~/.config/rdcli-py/conf.json`).
I can't give you an ETA because i'm quite busy these days and I don't have a lot of free time on my hand, but it's something i'll definitely look into, and i'll keep you updated.
In the meantime, you are more than welcome to sumbit apull-request if you feel like implementing this yourself.

**Comment by MrMitch** [comment]
as of version 0.8.1, you can configure the output directory permanently using the command
```bash
rdcli --config output_dir ~∕Downloads #~/Downloads is an exemple
```
This setting is only active for the user that launches the command (the settings are stored in `~/.config/rdcli-py/conf.json`, per user).

To uprgade `rdcli`, use 
```bash
sudo pip install rdcli --upgrade
```

**Comment by MrMitch** [comment]
cc @Schweinepriester

**Comment by Schweinepriester** [comment]
Slowpoke me: Thank you, great! :)

I guess the issue can be closed?

**Comment by MrMitch** [comment]
great, thank you for your feedback. if you have more idea, feel free to open as many issues as you like, i'd be glad to discuss how I can make them happen !
