### ISSUE TITLE
Can i install without root access?

### ISSUE THREAD

**Issue by ghost** [MrMitch/realdebrid-CLI#19]
Hi, i want to install this to my seedbox but i don't have root access there. Can i use something like `python setup.py install --prefix=$HOME`?

**Comment by MrMitch** [comment]
Hi !

Yes you can, but i'd recommend using the [`--home`](https://docs.python.org/2.0/inst/alt-install-prefix.html) option instead of the [`--prefix`](https://docs.python.org/2.0/inst/alt-install-home.html) option.

For example, you could do something like `python setup.py install --home=$HOME`.
Note that you might need to tweak your `$PYTHONPATH` environment variable for it to work proprely. The installer will help you with that if necessary.
